spring:
  aop:
    proxyTargetClass: true

eureka:
  instance:
    port: 8761
    hostname: localhost
    leaseRenewalIntervalInSeconds: 3
    instanceId: ${spring.application.name}:${random.uuid}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    fetchRegistry: true

zuul:
  retryable: true
  routes:
    messages-service: /messages/**
  add-proxy-headers: true