message:
  hello: Hello everybody !

spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  cloud:
      discovery:
        enabled: true
        serviceId: CONFIG-SERVER

server:
  port: ${port:8569}