message:
  hello: Hello everybody!

spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

server:
  port: ${port:8569}

eureka:
  instance:
    port: 8761
    leaseRenewalIntervalInSeconds: 10
    instanceId: ${spring.application.name}:${random.uuid}
    hostname: localhost
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/